border color changes when piece or square
macleanb/chess_public pull request #41
Opened 2024-04-24 20:20 UTC by JamesH34

is clicked

2024-04-24 21:14 UTC, macleanb requested changes
Overall I'm not sure this was the latest version you were working on...it doesn't really work for me.  Clicking a piece kind of works, but clicking a square doesn't get possible moves.  I made the necessary updates and I'm happy to push them to this branch if you guys are good with it.

2024-04-24 21:14 UTC, macleanb commented on frontend/cheapchess/src/components/Board.js
> +      // e.target.style.border = ''
We can probably delete 109 at this point.

2024-04-24 21:14 UTC, macleanb commented on frontend/cheapchess/src/components/Board.js
> +    // e.target.style.border = "5px solid red"; //make the square red when clicked
We can probably delete 113 at this point.

2024-04-24 21:14 UTC, macleanb commented on frontend/cheapchess/src/components/Board.js
> +    console.log(squareData)
We can probably comment out 105

2024-04-24 21:14 UTC, macleanb commented on frontend/cheapchess/src/components/Board.js
> +  const handlePieceClicked = async (e, pieceData, boardSquareData) => {
Overall, I recommend moving all the logic for getting possible moves out of handlePieceClicked and moving it to handleSquareClicked because we want the behavior to be the same, so we might as well just keep it in once place.  So basically, whenever a piece is clicked, the handlePieceClicked will do nothing for now and just propagate the event up to its parent square.

2024-04-24 21:14 UTC, macleanb commented on frontend/cheapchess/src/components/Piece.js
> +                  parentState?.handleSquareClicked(
I think we want to call handlePieceClicked here.  I suspect maybe you had already updated this...

2024-04-24 21:14 UTC, macleanb commented on frontend/cheapchess/src/components/Square.js
> +      className={ `${ parentState?.squareData?.color ? parentState.squareData.color : ''} ${parentState?.squareData === parentState?.selectedOriginSquare ? styles.borderRed : ''} ${styles.relativesqu
recommend doing styles.borderGreen instead

2024-04-24 21:14 UTC, macleanb commented on frontend/cheapchess/src/components/Square.module.css
> +.borderRed{
recommend .borderGreen

2024-04-24 21:14 UTC, macleanb commented on frontend/cheapchess/src/components/Square.module.css
> +  border: 5px solid red;
recommend 5px solid lightgreen

2024-04-24 21:15 UTC, macleanb approved these changes
Nice!

2024-04-24 21:16 UTC, macleanb requested changes
Please see comments

2024-04-25 14:06 UTC, errickbd commented
Thinking we should make the border color to this shade of 'orange' instead: rgb(255, 170, 0)

2024-04-25 21:17 UTC, closed without merging

2024-04-25 21:17 UTC, macleanb commented
Closing because this was resolved elsewhere (#43).