56 capture a piece
macleanb/chess_public pull request #64
Opened 2024-04-30 18:33 UTC by JamesH34

Updated Put view and Get view in views.py in the games_app. Players are able to capture pieces, and the related Cypress test passes.

2024-04-30 20:23 UTC, chsbca requested changes
![image](https://github.com/macleanb/chess_public/assets/155914185/a5181164-fbc7-4cf6-8434-65226f7fc275)

trying to do some testing to find bugs, and i found one.
To give context for the image above, on white's turn, they had a white rook on the upper left corner. I proceeded to capture black's rook right below it, but the game/database reflects the black rook on that spot but the white rook being gone, despite being the attacker.
It is currently black rook's turn, and upon piece selection, the database does not return any legal moves it can make, despite it having paths to do so. I think the confusion of the database and the frontend might be the reason why there's this weird bug.
I was able to consistently replicate the bug (3 times to be specific), and it seems to be the rank A rooks capturing each other having some weird behavior there

2024-04-30 20:23 UTC, chsbca commented on frontend/cheapchess/src/components/Board.js
> +    // } else {
did we want lines 38 to 54 commented out? This is the check that @macleanb put to verify if it's the player's turn to move or check if there is a second player to start the match with

2024-04-30 20:28 UTC, chsbca commented
Additional info on the bug I found, it seems to be some weird behavior with white capturing black. Once a move is made from white going to capture black's piece, the bug seems to be that sometimes black will come out on top.

2024-04-30 22:17 UTC, macleanb commented
I wrote a test (1c) on feature branch #67 if you want to check it out.  Branch 67 merged (includes) branch 56, but I'm not seeing this test reproducing the buggy behavior.

2024-04-30 22:23 UTC, macleanb commented on frontend/cheapchess/src/components/Board.js
> +    // } else {
Good catch Chris.  We do not want those lines commented out.  We need to uncomment them and re-commit.  Thanks!

2024-04-30 22:46 UTC, chsbca commented
I'll try to replicate the behavior on my end too come tomorrow morning. I'll use a screen recording software too to hopefully capture that behavior and see if yall can replicate it and check if it produces the same results.

2024-04-30 23:27 UTC, macleanb commented
I have a hunch.  In Issue #67 (the test file) I added some print statements to illustrate what I suspect is happening.

When we do:
```            
captured_piece = updated_game.pieces.filter(
                current_file = destination_square_id[0],
                current_rank = destination_square_id[1]
            ).exclude(pk=updated_piece.id).first()
```
...I suspect that sometimes more than one piece is somehow remaining in the filter result, despite our attempts to exclude the piece we just selected.  I'm no expert on exclude, but I wonder if it isn't working the way we expected.

So I wrote a test below that:
```
            # test
            test_captured_pieces = updated_game.pieces.filter(
                current_file = destination_square_id[0],
                current_rank = destination_square_id[1]
            ).exclude(pk=updated_piece.id)
            print('Here in games_app views.py, number of captured pieces: ')
            print(test_captured_pieces.count())
```

Sure enough -- on a few occasions when pieces are captured, I see "2" printed out once in a while (with knights and pawns, but not rooks), indicating that the filtered captured pieces have more than one object even though we tried to filter out our piece that moved.  This doesn't always happen.  But when it does, calling .first() on the filtered pieces will probably return a light or a dark piece randomly.

We could read up on the exclude method, or instead just include the opponent's color in the filter and get rid of exclude() altogether.

2024-05-01 16:17 UTC, JamesH34 commented
Feature is complete in accordance with specification. Passing Cypress tests.
![Screenshot 2024-05-01 at 12 15 15 PM](https://github.com/macleanb/chess_public/assets/155463962/de797172-bc01-4866-b17d-169bb70e28bc)

2024-05-01 18:27 UTC, chsbca approved these changes

2024-05-01 18:27 UTC, merged